---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"

- name: Install influxdb package for RedHat
  yum:
    name: influxdb
  when: ansible_os_family == 'RedHat'
  notify:
    - Restart influxdb service
  tags:
    - influxdb_pkg

- name: Install influxdb package for Debian
  apt:
    name: influxdb
  when: ansible_os_family == 'Debian'
  notify:
    - Restart influxdb service
  tags:
    - influxdb_pkg

- name: Symlink init.d script
  file:
    src: /opt/influxdb/current/scripts/init.sh
    path: /etc/init.d/influxdb
    state: link

- name: Create InfluxDB configuration file
  template:
    src: config.toml.j2
    dest: /opt/influxdb/shared/config.toml
  notify:
    - Restart influxdb service
  tags:
    - influxdb_config

- name: Make influxdb service running
  service:
    name: influxdb
    state: started
    enabled: yes
