---

- name: Restart influxdb service
  service:
    name: "{{ influxdb_service }}"
    state: restarted
  when: >
    influxdb_service_started is not defined or
    not influxdb_service_started.changed
